### ISSUE TITLE
Modulo de Ordenes-Dashboar Principal

### ISSUE THREAD

**Issue by ElmerMartinz** [ResBar-2020/ResBar#4]

**Comment by calderonperaza** [comment]
**Historia del usuario**
como usuario del sistema necesito visualizar y administrar todas las ordenes.

**Criterios de Aceptación**
Asegúrese que el usuario pueda:
1. Ordenar las ordenes por: mesa, mesero, cliente y N de orden
2. Poder filtrar escribiendo un texto y que se busquen dichas ordenes.
3. dar doble clic sobre una orden y que se muestre su detalle (Read Only)
4. redireccionar para agregar una orden, agregar mas productos, editar y eliminar una orden
5. mostrar los mensajes de confirmacion adecuadamente
