### ISSUE TITLE
Módulo de Categorias

### ISSUE THREAD

**Issue by kevin-Oz** [ResBar-2020/ResBar#5]
categorías de los productos a administrar en sistema ResBar.

**Comment by calderonperaza** [comment]
Observaciones:

1. en el modal de agregar nueva categoria, quita el campo # del id, puesto que se genera automaticamente.
2. Al eliminar una categoria, pide confirmacion con un modal 
3. Al modificar una categoria el campo # debe ser readonly

**Comment by calderonperaza** [comment]
**Historia del usuario**
necesito poder administrar las categorias del sitema.

**Criterios de Aceptación**
1. debo poder filtrar las categorias
2. agregar una nueva categoría (que no permita agregar una con el nombre en blanco)
3. modificar una categoría existente cambiando nombre por ejemplo
4. eliminar una categoría (que pida confirmación para poder eliminar)
5. para cada acción que actualice correctamente la base de datos mongoDB
