### ISSUE TITLE
Modulo de Ordenes - Modificar Orden

### ISSUE THREAD

**Issue by Gabriel-Ramirez** [ResBar-2020/ResBar#6]

**Comment by calderonperaza** [comment]
**Historia del usuario**
como usuario del sistema necesito modificar una orden.

**Criterios de Aceptación**
Asegúrese que el usuario pueda:
1. visualizar los datos y detalle de productos de la orden(se recibe un parametro ID que indica la orden a modificar)
2. modificar los datos generales de la orden
3. modificar las cantidades de los productos y/o eliminar un producto de dicha orden.
4. eliminar la orden completa, previo a una conformación.
5. redireccionar al dashboard ordenes enviando un mensaje indicando que se modificó correctamente la orden ID tal
