### ISSUE TITLE
Modulo de Ordenes - Agregar Mas Productos

### ISSUE THREAD

**Issue by JonaHdz22-GH** [ResBar-2020/ResBar#7]

**Comment by calderonperaza** [comment]
Solo una pequeña observacion, lo responsive cuando se vuelve para celular, los botones de las categorias deberian hacerse mas pequeños para que se vean mejor, y el modal de confirmar, tambien en el tamaño mas pequeño, los datos del encabezado (mesero, mesa, orden, etc) ocupan una linea cada uno, lo que hace que ocupen mucho espacio, hay que reducirlo en el modo sm

**Comment by JonaHdz22-GH** [comment]
Recibido

**Comment by calderonperaza** [comment]
**Historia del usuario**
como usuario del sistema necesito agregar mas productos a una orden ya existente.

**Criterios de Aceptación**
Asegúrese que el usuario pueda:
1. visualizar el menu de productos, filtrando por categorias y texto
2. seleccionar los productos que desea agregar a la orden haciendo clic en el boton mas o menos (validando que no hayan cantidades negativas).
3. visualizar el resumen de los productos a agregar, donde solo se muestren los productos con cantidades de 1 o mas obviamente.
4. actualizar los productos de la orden ya existente en la base de datos, los productos que ya estaban agregados, aumentar la cantidad, los productos que no estaban agregados, insertarlos,  calculando el total de orden correctamente (en base al precio unitario, la cantidad, subtotal).
5. redireccionar al dashboard ordenes enviando un mensaje indicando que se agregaron mas productos a la orden N1234 correctamente.

Recuerde que el ID de la orden se recibe como un parametro.
