### ISSUE TITLE
Modulo de Ordenes-Cobrar Orden

### ISSUE THREAD

**Issue by majm5555** [ResBar-2020/ResBar#8]

**Comment by calderonperaza** [comment]
pon el total de la Orden en negrita, para que resalte mas, y el menaje que mandas a ordenes.htm debe indicar la orden, el total de la orden, el efectivo entregado y el vuelto

**Comment by calderonperaza** [comment]
**Historia del usuario**
como usuario del sistema necesito cobrar una orden.

**Criterios de Aceptación**
Asegúrese que el usuario pueda:
1. ver los datos generales y el detalle de la orden
2. ver de forma resaltada el total monetario de la orden, re calculando el total de la orden, para que sea la correcta sumatoria de los precios unitarios por la cantidad.
3. digitar el monto del efectivo.
4. realizar el cobro de la orden: cambiando el estado de la orden a "C" que significa cobrada
5. guardar en la coleccion ResumendeVentas la venta: si ya habia un documento con venta de ese dia, actualizar los productos insertando los de la venta actual, si no existen pues insertarlos, y sumar el valor de la venta del dia, mas el total de la orden cobrada.
5. redireccionar al dashboard ordenes enviando un mensaje indicando que se a cobro la orden No 123a12 con un total de $12.34 efectivo de $20.00 y un cambio de $7.76
