### ISSUE TITLE
Modulo de Ordenes- Crear Nueva orden

### ISSUE THREAD

**Issue by brahhms** [ResBar-2020/ResBar#9]
Agregar nueva orden

**Comment by calderonperaza** [comment]
Solo les falta mostrar el modal de la confirmación de los productos

**Comment by calderonperaza** [comment]
Metámosle jóvenes, solo ustedes tienen pendiente una parte, asi completamos y pasamos a desarrollar la funcionalidad

**Comment by calderonperaza** [comment]
**Historia del usuario**
como usuario del sistema necesito agregar una nueva orden.

**Criterios de Aceptación**
Asegúrese que el usuario pueda:
1. introducir los datos generales de la orden
2. ver  y filtrar el menu de productos, y poder seleccionar facilmente dichos productos agregando cantidades, validando que no hayan cantidades negativas.
3. visualizar el resumen de los productos a agregar, donde solo se muestren los productos con cantidades de 1 o mas obviamente.
4. agregar a la base de datos la nueva orden, calculando el total de orden correctamente (en base al precio unitario, la cantidad, subtotal)
5. redireccionar al dashboard ordenes enviando un mensaje indicando que se agrego una nueva orden

**Comment by calderonperaza** [comment]
comentarios:
El campo Cliente: la validacion no permite poner espacios, por ejemplo poner: Sr Perdomo lo marca como invalido

La tabla donde se muestran los productos puede bajar un poco mas, y hacer menos anchos los botones de cancelar y verificar, asi se visualizan mas productos
